version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  
conda:
  environment: environment.yaml

python:
  install:
    - method: pip
      path: .
      packages:
        - sphinx==7.1.2
        - sphinx-rtd-theme==1.3.0rc1

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py