name: pyccl_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - pyccl==2.8.0
  - numpy==1.* #Avoid using numpy 2.0
  - scipy
  - joblib
  - tqdm
  - healpy

  - ipykernel #Used just for putting env in jupyter kernel
  - pip  

  - pip:
    - numba