name: pyccl_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - pyccl==2.*
  - numpy==1.*
  - scipy
  - joblib
  - tqdm
  - healpy

  - ipykernel #Used just for putting env in jupyter kernel
  - pip  

  - pip:
    - numba