name: pyccl_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - pyccl==2.*
  - numpy
  - scipy
  - joblib
  - tqdm
  - healpy

  - ipykernel #Used just for putting env in jupyter kernel
  - pip  

  - pip:
    - numba

    - sphinx==7.1.2 #Just for doc building
    - sphinx-rtd-theme==1.3.0rc1 #Just for doc building
    