name: pyccl_env

channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - pyccl>=3.1.2
  - numpy==1.* #Avoid using numpy 2.0
  - scipy>=1.12
  - joblib
  - tqdm
  - healpy

  - ipykernel #Used just for putting env in jupyter kernel
  - pip  

  - pip:
    - numba